---
# tasks file for apigee-opdk-setup-edge-saml-config/

- name: Update cache with key and value
  cache:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: 'edgeui_response_file_path', value: '{{ edgeui_response_file_path }}' }
  - { key: 'edgeui_public_uris', value: '{{ edgeui_public_uris }}' }

- name: Create Edge UI Response File
  become: true
  template:
    src: "{{ edgeui_response_file_name }}.j2"
    dest: "{{ edgeui_response_file_path }}"
    mode: 0644

- name: Configure SSO on Edge UI
  shell: "/opt/apigee/apigee-service/bin/apigee-service edge-ui configure-sso -f {{ edgeui_response_file_path }}"